import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

/* 
define an API call in the front end 
any API call within "adminApi" will be put here
*/
export const api = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: process.env.REACT_APP_BASE_URL }),
  reducerPath: "adminApi",
  tagTypes: ["User"], // optional
  endpoints: (build) => ({ // all endpoints go into this object
    getUser: build.query({ // if `get` request use build.query(), else use build.mutation()
      query: (id) => `general/user/${id}`,
      providesTags: ["User"], // optional
    }),
  }),
});

/* 
the naming convention for the custom hook must be followed 
the query hooks are automatically generated by reduxjs toolkit that follows a specific naming convention
prefix `use` and suffix `query`
*/
export const { useGetUserQuery } = api;
