/* Use { } when importing when it is a named export and not when it is a default export*/

import React from "react";
import ReactDOM from "react-dom/client";
import "./index.css";
import App from "./App";
import { configureStore } from "@reduxjs/toolkit";
import { globalSlice } from "state/index"; // we've specified the baseUrl to be 'src'
import { Provider } from "react-redux";
import { setupListeners } from "@reduxjs/toolkit/query";
import { api } from "state/api";

const store = configureStore({
  reducer: {
    /* 
    `sliceName`: `objectVariableName`.reducer
    */
    global: globalSlice.reducer, 

    /* 
    `[]` are used as a way to define a dynamic property name in JavaScript object 
    api.reducer is automatically generated by RTK query
    */
    adminApi: api.reducer, // `api.reducer` is automatically generated Redux reducer by Redux Toolkit. It is responsible for managing API state.
  },
  middleware: (getDefault) => getDefault().concat(api.middleware)
});
setupListeners(store.dispatch);

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(
  <React.StrictMode>
    <Provider store={store}>
      <App />
    </Provider>
  </React.StrictMode>
);
